"""Utility modules for boofun package."""

from .finite_fields import HAS_GALOIS, GFField, get_field
from .math import (
    binary_tuple_to_int,
    bits,
    cartesian,
    generate_permutations,
    hamming_distance,
    hamming_weight,
    int_to_binary_tuple,
    krawchouk,
    krawchouk2,
    num2bin_list,
    over,
    popcnt,
    poppar,
    subsets,
    tensor_product,
)
from .number_theory import (
    binomial,
    binomial_sum,
    crt,
    euler_phi,
    factor,
    gcd,
    invmod,
    is_prime,
    lcm,
    mobius,
    prime_factorization,
    prime_sieve,
    totient,
)

__all__ = [
    "HAS_GALOIS",
    "GFField",
    "binary_tuple_to_int",
    "binomial",
    "binomial_sum",
    "bits",
    "cartesian",
    "crt",
    "euler_phi",
    "factor",
    # Number theory
    "gcd",
    "generate_permutations",
    # Finite fields
    "get_field",
    "hamming_distance",
    "hamming_weight",
    "int_to_binary_tuple",
    "invmod",
    "is_prime",
    "krawchouk",
    "krawchouk2",
    "lcm",
    "mobius",
    "num2bin_list",
    "over",
    # Math utilities
    "popcnt",
    "poppar",
    "prime_factorization",
    "prime_sieve",
    "subsets",
    "tensor_product",
    "totient",
]
